{% set name = "equilibrator-api" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 65f8cacc1ee6a54e22ef1b6149d26394468bd1a8a0e5dc4aff2b79300ce3f49b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41
    - setuptools-scm
    - wheel
    - setuptools-git-versioning >=2.0,<3
    - pip
  run:
    - python >={{ python_min }}
    - pyparsing ~=3.1
    - python-slugify ~=8.0
    - equilibrator-cache ~=0.6.1
    - component-contribution ~=0.6.0

test:
  imports:
    - equilibrator_api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/equilibrator/equilibrator-api
  summary: Calculation of standard thermodynamic potentials of biochemical reactions.
  license: MIT
  license_file: LICENSE
  description: >
    A command-line tool with minimal dependencies for the calculation of standard thermodynamic potentials of biochemical reactions using the data found on eQuilibrator (http://equilibrator.weizmann.ac.il/).  Does not require any network connections after an initial database download.
  dev_url: https://gitlab.com/equilibrator/equilibrator-api

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
