{% set name = "equilibrator-api" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-api-{{ version }}.tar.gz
  sha256: 7c1d0a2029b0e07f10956f61df191768409729152eb570bb77a9d8ed946a822d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - component-contribution ~=0.5.2
    - equilibrator-cache ~=0.5.4
    - pyparsing ~=3.0
    - python-slugify ~=5.0

test:
  imports:
    - equilibrator_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/equilibrator-api
  summary: Calculation of standard thermodynamic potentials of biochemical reactions.
  license: MIT
  license_file: LICENSE
  description: >
    A command-line tool with minimal dependencies for the calculation of standard thermodynamic potentials of biochemical reactions using the data found on eQuilibrator (http://equilibrator.weizmann.ac.il/).  Does not require any network connections after an initial database download.
  dev_url: https://gitlab.com/equilibrator/equilibrator-api

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
