{% set name = "equilibrator-api" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-api-{{ version }}.tar.gz
  sha256: 1a06cf783e37c3d583bfeae9bf35f886e9ef56ebc8706ccde8342d1838d33959

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - equilibrator-cache ~=0.4.2
    - component-contribution ~=0.4.2
    - pyparsing ~=2.4
    - python >=3.6
    - python-slugify ~=4.0

test:
  imports:
    - equilibrator_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/equilibrator-api
  summary: Calculation of standard thermodynamic potentials of biochemical reactions.
  license: MIT
  license_file: LICENSE
  description: >
    A command-line tool with minimal dependencies for the calculation of standard thermodynamic potentials of biochemical reactions using the data found on eQuilibrator (http://equilibrator.weizmann.ac.il/).  Does not require any network connections after an initial database download.
  dev_url: https://gitlab.com/equilibrator/equilibrator-api

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
