{% set name = "equilibrator-api" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/equilibrator-api-{{ version }}.tar.gz
  sha256: e0f340dadb11a6045ddffa6468ce58d5514bf34a0f17d8462b3888d83eb70529

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - equilibrator-cache ~=0.4.3
    - component-contribution ~=0.4.4
    - pyparsing ~=3.0
    - python >=3.6
    - python-slugify ~=5.0

test:
  imports:
    - equilibrator_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/equilibrator-api
  summary: Calculation of standard thermodynamic potentials of biochemical reactions.
  license: MIT
  license_file: LICENSE
  description: >
    A command-line tool with minimal dependencies for the calculation of standard thermodynamic potentials of biochemical reactions using the data found on eQuilibrator (http://equilibrator.weizmann.ac.il/).  Does not require any network connections after an initial database download.
  dev_url: https://gitlab.com/equilibrator/equilibrator-api

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
